In [2]:
import os
import pickle
import pandas as pd

In [3]:
df = pd.read_csv('train_feat.csv')
df.head()

,enroll_id,all#count,session#count,seek_video#num,play_video#num,pause_video#num,stop_video#num,load_video#num,problem_get#num,problem_check#num,...,truth,username,course_id,age,gender,education,user_enroll_num,course_enroll_num,cluster_label,course_category
0,772,-0.228387,-0.228387,-0.243043,-0.296739,-0.333535,-0.059298,-0.480968,-0.042412,-0.305844,...,1,5981,course-v1:TsinghuaX+70800232X+2015_T2,1.504677,1,3,-0.007581,-0.138544,2,0
1,773,-0.204883,-0.204883,-0.115253,-0.242027,-0.296012,-0.059298,-0.445267,-0.042412,-0.305844,...,1,1544995,course-v1:TsinghuaX+70800232X+2015_T2,-0.599969,0,0,-0.360012,-0.138544,2,0
2,774,-0.139320,-0.139320,-0.051358,-0.105248,-0.208460,-0.057709,-0.195358,-0.042412,-0.305844,...,1,1072798,course-v1:TsinghuaX+70800232X+2015_T2,-0.599969,0,0,-0.095689,-0.138544,2,0
3,776,-0.207357,-0.207357,-0.243043,-0.255705,-0.296012,-0.057709,-0.409566,-0.042412,-0.305844,...,0,561867,course-v1:TsinghuaX+70800232X+2015_T2,2.085269,2,6,-0.007581,-0.138544,2,0
4,777,-0.225912,-0.225912,-0.243043,-0.296739,-0.333535,-0.059298,-0.480968,-0.042412,-0.305844,...,1,1368125,course-v1:TsinghuaX+70800232X+2015_T2,-0.599969,0,0,0.432957,-0.138544,3,0

In [4]:
df['labels'] = df['truth']

# Drop unnecessary columns
df.drop(['truth'], axis=1, inplace=True)

# Define feature columns
feature_columns = ['all#count', 'session#count', 'seek_video#num',
       'play_video#num', 'pause_video#num', 'stop_video#num', 'load_video#num',
       'problem_get#num', 'problem_check#num', 'problem_save#num',
       'reset_problem#num', 'problem_check_correct#num',
       'problem_check_incorrect#num', 'create_thread#num',
       'create_comment#num', 'delete_thread#num', 'delete_comment#num',
       'click_info#num', 'click_courseware#num', 'click_about#num',
       'click_forum#num', 'click_progress#num', 'close_courseware#num', 'course_id',
       'user_enroll_num', 'course_enroll_num', 'cluster_label',
       'course_category']

# Create data file using column names
data_file = {'data':{}, 'available_demographics': ['gender', 'age', 'education']}
for i_row, row in df.iterrows():
    data_file['data'][i_row] = {
        'learner_id': int(i_row),
        'features': row[feature_columns].values,
        'gender': int(row['gender']),
        'age': int(row['age']),
        'education': int(row['education']),
        'binary_label': int(row['labels'])
    }

In [6]:
with open('../data/xuetangx/data_dictionary.pkl', 'wb') as fp:
    pickle.dump(data_file, fp)